"use client";

import React from "react";
import styles from "./DashboardGrid.module.css";
import ChartRenderer from "../visualizations/ChartRenderer";
import { TrendingUp } from "lucide-react";

export default function DashboardGrid() {
  return (
    <section className={styles.bentoContainer}>
      
      {/* ---------- Large chart card (spans two columns) ----------- */}
      <article className={`${styles.card} ${styles.largeCard}`}>
        <div className={styles.cardHeader}>
          <div>
            <h2 className={styles.cardTitle}>Primary Metric Trend</h2>
            <p className={styles.cardSubtitle}>AI Prediction vs Actuals</p>
          </div>
        </div>
        <div className={styles.cardContent}>
          <div className={styles.chartPlaceholder}>
            <TrendingUp size={48} className={styles.chartIcon} />
            <p>Connect a database to generate predictive charts</p>
          </div>
        </div>
      </article>

      {/* ---------- Medium card (spans two columns) ----------- */}
      <article className={`${styles.card} ${styles.mediumCard}`}>
        <div className={styles.cardHeader}>
          <div>
            <h2 className={styles.cardTitle}>Key Insights</h2>
            <p className={styles.cardSubtitle}>Auto-generated by AI</p>
          </div>
        </div>
        <div className={styles.cardContent} style={{ justifyContent: 'flex-start' }}>
          <ul className={styles.insightList}>
            <li><span className={styles.bullet}></span> Connect a data source to see automatically detected anomalies</li>
            <li><span className={styles.bullet}></span> Query your data using natural language to uncover hidden trends</li>
            <li><span className={styles.bullet}></span> Save your most used queries as interactive dashboards</li>
          </ul>
        </div>
      </article>

      {/* ---------- Small cards (span one column) ----------- */}
      <article className={`${styles.card} ${styles.smallCard}`}>
        <div className={styles.cardHeader}>
          <h4 className={styles.cardTitle}>Total Records</h4>
        </div>
        <div className={styles.cardContent}>
          <div className={styles.bigNumber}>---</div>
          <div className={`${styles.trend} ${styles.up}`}>Waiting for connection</div>
        </div>
      </article>

      <article className={`${styles.card} ${styles.smallCard}`}>
        <div className={styles.cardHeader}>
          <h4 className={styles.cardTitle}>Anomaly Score</h4>
        </div>
        <div className={styles.cardContent}>
          <p className={styles.metricValue}>0.04</p>
          <p className={`${styles.metricTrend} ${styles.trendDown}`}>-0.02 from baseline</p>
        </div>
      </article>

      <article className={`${styles.card} ${styles.smallCard}`}>
        <div className={styles.cardHeader}>
          <h4 className={styles.cardTitle}>Data Quality</h4>
        </div>
        <div className={styles.cardContent}>
          <p className={styles.metricValue}>98.2%</p>
          <p className={`${styles.metricTrend} ${styles.trendUp}`}>Optimal</p>
        </div>
      </article>
      
      <article className={`${styles.card} ${styles.smallCard}`}>
        <div className={styles.cardHeader}>
          <h4 className={styles.cardTitle}>API Latency</h4>
        </div>
        <div className={styles.cardContent}>
          <p className={styles.metricValue}>124ms</p>
          <p className={`${styles.metricTrend} ${styles.trendDown}`}>-15ms improvement</p>
        </div>
      </article>

    </section>
  );
}
