"""QueryHistory ORM model.

Tracks every natural-language → SQL query execution for auditing,
cost tracking, and agent learning.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base


class QueryHistory(Base):
    """Immutable log of executed queries."""

    __tablename__ = "query_history"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    connection_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("database_connections.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    natural_language_query: Mapped[str] = mapped_column(
        Text, nullable=False,
        doc="The original question asked by the user",
    )
    generated_sql: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        doc="SQL generated by the SQL Agent",
    )
    status: Mapped[str] = mapped_column(
        String(50), default="pending", nullable=False,
        doc="QueryStatus enum value",
    )
    result_row_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    result_data: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        doc="JSON snapshot of up to 50 rows of data",
    )
    result_summary: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        doc="AI-generated plain-English summary of the results",
    )
    narrative: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        doc="Premium executive narrative of the data and stats",
    )
    chart_config: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        doc="JSON string containing chart configuration",
    )
    execution_time_ms: Mapped[float | None] = mapped_column(Float, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )

    # Relationships
    user: Mapped["User"] = relationship(back_populates="query_history")  # noqa: F821
    connection: Mapped["DatabaseConnection"] = relationship(back_populates="queries")  # noqa: F821
    chat_session: Mapped["ChatSession"] = relationship(back_populates="queries")  # noqa: F821

    def __repr__(self) -> str:
        return f"<QueryHistory {self.id} status={self.status}>"
