"""add chart_config

Revision ID: 03b253980af7
Revises: 5df3879dfd83
Create Date: 2026-07-02 09:54:34.669458+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b253980af7'
down_revision: Union[str, None] = '5df3879dfd83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_history', sa.Column('chart_config', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_history', 'chart_config')
    # ### end Alembic commands ###
