"""Add narrative column

Revision ID: f2e2f670dab5
Revises: 973e62cc871d
Create Date: 2026-07-04 01:59:37.244719+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e2f670dab5'
down_revision: Union[str, None] = '973e62cc871d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usa_cars')
    op.add_column('query_history', sa.Column('narrative', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_history', 'narrative')
    op.create_table('usa_cars',
    sa.Column('price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mileage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vin', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lot', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
